version: "3.7"

services:
  transaction-query-service:
    build:
      context: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: >
      sh -c "
            npx prisma generate dev &&
            npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true