version: "3.7"

services:
  user-service-db:
    hostname: user-service-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data/
  user-service:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: >
      sh -c "
            npx prisma db push &&
            npx prisma generate dev &&
            npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      user-service-db:
        condition: service_healthy